"use client";

import { useMemo, useState } from "react";
import { WebsiteSchema } from "@aiwebbuilder/schema";

const initialSchema = {
  metadata: { title: "Demo Site", description: "Generated by AI" },
  theme: {
    colors: { primary: "#1D4ED8", secondary: "#06B6D4", background: "#FFFFFF", text: "#111827" },
    fonts: { heading: "Inter", body: "Inter" }
  },
  sections: [{ id: "hero-1", type: "hero", inputs: { title: "Launch fast", body: "Build and publish in minutes" } }],
  security: { allowExternalScripts: false, csp: "default-src 'self'; script-src 'none'; object-src 'none'" }
};

export default function EditorPage() {
  const [schemaText, setSchemaText] = useState(JSON.stringify(initialSchema, null, 2));
  const previewDoc = useMemo(() => {
    try {
      const parsed = WebsiteSchema.parse(JSON.parse(schemaText));
      return `<html><body><h1>${parsed.metadata.title}</h1><p>${parsed.metadata.description}</p></body></html>`;
    } catch {
      return "<html><body><pre>Schema validation failed.</pre></body></html>";
    }
  }, [schemaText]);

  return (
    <main>
      <h1>Schema Editor (Monaco-ready)</h1>
      <textarea rows={24} cols={90} value={schemaText} onChange={(e) => setSchemaText(e.target.value)} />
      <h2>Live Preview</h2>
      <iframe
        sandbox="allow-same-origin"
        csp="default-src 'none'; style-src 'unsafe-inline'; img-src data:;"
        srcDoc={previewDoc}
        style={{ width: "100%", minHeight: 250, border: "1px solid #ddd" }}
      />
    </main>
  );
}
